"""SentinelFW Active/Passive High Availability (HA) & Failover Engine.

Provides VRRP-based stateful cluster coordination, session replication,
split-brain witness validation, and keepalived configuration generation.
"""
import copy
import logging
import threading
import time
from typing import Callable, Dict, List, Optional, Tuple

logger = logging.getLogger("sentinelfw.ha")


class NodeRole:
    MASTER = "MASTER"
    BACKUP = "BACKUP"
    FAULT = "FAULT"


class HAClusterConfig:
    def __init__(self, vrid: int = 51, priority: int = 100,
                 peer_ip: str = "192.168.100.2",
                 sync_interface: str = "eth2",
                 virtual_ips: Optional[List[str]] = None,
                 witness_ip: str = "8.8.8.8",
                 heartbeat_interval: float = 1.0,
                 failover_timeout: float = 3.0):
        self.vrid = vrid
        self.priority = priority
        self.peer_ip = peer_ip
        self.sync_interface = sync_interface
        self.virtual_ips = virtual_ips or ["198.51.100.1/24", "192.168.1.1/24"]
        self.witness_ip = witness_ip
        self.heartbeat_interval = heartbeat_interval
        self.failover_timeout = failover_timeout


class FailoverManager:
    """Orchestrates appliance cluster state, heartbeats, and split-brain fencing."""

    def __init__(self, config: HAClusterConfig,
                 witness_check_fn: Optional[Callable[[str], bool]] = None):
        self.cfg = config
        self.witness_check_fn = witness_check_fn or (lambda ip: True)
        self.role = NodeRole.MASTER if config.priority > 100 else NodeRole.BACKUP
        self.last_peer_heartbeat = time.time()
        self.synced_bans: set = set()
        self.synced_sessions: int = 0
        self.failover_events: List[dict] = []
        self._lock = threading.RLock()

    def record_peer_heartbeat(self, peer_priority: int, peer_role: str, timestamp: Optional[float] = None):
        """Processes a received heartbeat advertisement from the HA cluster peer."""
        now = timestamp if timestamp is not None else time.time()
        with self._lock:
            self.last_peer_heartbeat = now

            # If peer has higher priority and claims MASTER, demote to BACKUP
            if peer_role == NodeRole.MASTER and peer_priority > self.cfg.priority:
                if self.role == NodeRole.MASTER:
                    self._transition_to(NodeRole.BACKUP, f"Yielding to higher priority peer ({peer_priority} > {self.cfg.priority})")

    def check_health_and_failover(self, now: Optional[float] = None) -> str:
        """Evaluates peer heartbeat freshness and triggers failover promotion if peer is down."""
        current_time = now if now is not None else time.time()
        with self._lock:
            time_since_last = current_time - self.last_peer_heartbeat

            # If peer missed heartbeats beyond failover timeout
            if time_since_last > self.cfg.failover_timeout:
                if self.role == NodeRole.BACKUP:
                    # Split-brain prevention: verify external witness before promoting
                    witness_alive = self.witness_check_fn(self.cfg.witness_ip)
                    if witness_alive:
                        self._transition_to(NodeRole.MASTER, f"Peer missed heartbeats ({time_since_last:.1f}s); witness alive, promoting to MASTER")
                    else:
                        self._transition_to(NodeRole.FAULT, "Peer heartbeat lost and witness unreachable (fencing against split-brain)")

            return self.role

    def _transition_to(self, new_role: str, reason: str):
        old_role = self.role
        self.role = new_role
        event_entry = {
            "timestamp": time.time(),
            "from_role": old_role,
            "to_role": new_role,
            "reason": reason,
        }
        self.failover_events.append(event_entry)
        logger.warning(f"HA Role Transition: {old_role} -> {new_role} ({reason})")

    def sync_state(self, bans: List[str], session_count: int):
        with self._lock:
            self.synced_bans.update(bans)
            self.synced_sessions = session_count

    def generate_keepalived_conf(self) -> str:
        """Generates production keepalived.conf configuration."""
        vips_str = "\n        ".join(self.cfg.virtual_ips)
        conf = f"""# keepalived.conf generated by SentinelFW
global_defs {{
    router_id SentinelFW_Node_{self.cfg.priority}
    enable_script_security
}}

vrrp_instance VI_{self.cfg.vrid} {{
    state {self.role}
    interface {self.cfg.sync_interface}
    virtual_router_id {self.cfg.vrid}
    priority {self.cfg.priority}
    advert_int {int(self.cfg.heartbeat_interval)}

    unicast_peer {{
        {self.cfg.peer_ip}
    }}

    virtual_ipaddress {{
        {vips_str}
    }}
}}
"""
        return conf
