"""SentinelFW Enterprise VPN Subsystem (WireGuard & IPsec).

Provides operational management, IPAM, and configuration generators for:
- WireGuard peer lifecycle, dynamic IPAM, and client profile provisioning
- IPsec site-to-site orchestration with strongSwan swanctl.conf
- Zero private key exposure across status APIs
"""
import base64
import ipaddress
import secrets
import threading
import time
from typing import Dict, List, Optional, Tuple


class WireGuardPeer:
    def __init__(self, username: str, public_key: str, assigned_ip: str,
                 allowed_ips: Optional[List[str]] = None, endpoint: str = ""):
        self.username = username
        self.public_key = public_key
        self.assigned_ip = assigned_ip
        self.allowed_ips = allowed_ips or [f"{assigned_ip}/32"]
        self.endpoint = endpoint
        self.created_at = time.time()
        self.last_handshake = 0.0
        self.rx_bytes = 0
        self.tx_bytes = 0
        self.active = True

    def to_dict(self) -> dict:
        return {
            "username": self.username,
            "public_key": self.public_key,
            "assigned_ip": self.assigned_ip,
            "allowed_ips": self.allowed_ips,
            "endpoint": self.endpoint,
            "active": self.active,
            "rx_bytes": self.rx_bytes,
            "tx_bytes": self.tx_bytes,
            "last_handshake": self.last_handshake,
        }


class WireGuardServer:
    """Manages the WireGuard kernel/userspace interface and client IPAM."""

    def __init__(self, interface: str = "wg0", port: int = 51820,
                 subnet_cidr: str = "10.8.0.0/24", endpoint: str = "vpn.company.com"):
        self.interface = interface
        self.port = port
        self.endpoint = f"{endpoint}:{port}"
        self.subnet = ipaddress.ip_network(subnet_cidr)
        self.server_ip = str(list(self.subnet.hosts())[0])  # e.g. 10.8.0.1
        self._server_priv = secrets.token_urlsafe(32)[:44]  # Safe synthetic Curve25519 token
        self.server_pub = secrets.token_urlsafe(32)[:44]
        self._peers: Dict[str, WireGuardPeer] = {}  # username -> peer
        self._assigned_ips: Dict[str, str] = {self.server_ip: "server"}
        self._lock = threading.RLock()

    def _allocate_ip(self) -> str:
        for host in self.subnet.hosts():
            ip_str = str(host)
            if ip_str not in self._assigned_ips:
                return ip_str
        raise RuntimeError("WireGuard VPN subnet address exhaustion")

    def add_peer(self, username: str, public_key: str,
                 allowed_ips: Optional[List[str]] = None) -> WireGuardPeer:
        """Registers a new WireGuard client peer with dynamic IP allocation."""
        with self._lock:
            if username in self._peers:
                return self._peers[username]

            assigned_ip = self._allocate_ip()
            self._assigned_ips[assigned_ip] = username

            peer = WireGuardPeer(
                username=username,
                public_key=public_key,
                assigned_ip=assigned_ip,
                allowed_ips=allowed_ips or [f"{assigned_ip}/32"],
            )
            self._peers[username] = peer
            return peer

    def revoke_peer(self, username: str) -> bool:
        """Revokes a WireGuard peer and frees its IPAM address."""
        with self._lock:
            peer = self._peers.pop(username, None)
            if peer:
                self._assigned_ips.pop(peer.assigned_ip, None)
                return True
            return False

    def list_peers(self) -> List[dict]:
        with self._lock:
            return [p.to_dict() for p in self._peers.values()]

    def generate_server_conf(self) -> str:
        """Generates a complete /etc/wireguard/wg0.conf server configuration."""
        lines = [
            f"# Generated by SentinelFW WireGuard Orchestrator",
            f"[Interface]",
            f"Address = {self.server_ip}/{self.subnet.prefixlen}",
            f"ListenPort = {self.port}",
            f"PrivateKey = {self._server_priv}",
            f"",
        ]
        with self._lock:
            for p in self._peers.values():
                if not p.active:
                    continue
                lines.extend([
                    f"[Peer]",
                    f"# User: {p.username}",
                    f"PublicKey = {p.public_key}",
                    f"AllowedIPs = {', '.join(p.allowed_ips)}",
                    f"",
                ])
        return "\n".join(lines)

    def generate_client_conf(self, username: str, client_priv: str,
                             dns_server: str = "10.8.0.1") -> str:
        """Generates a client .conf profile for imported connections."""
        with self._lock:
            peer = self._peers.get(username)
            if not peer:
                raise ValueError(f"Peer {username} not found")

            lines = [
                f"[Interface]",
                f"PrivateKey = {client_priv}",
                f"Address = {peer.assigned_ip}/{self.subnet.prefixlen}",
                f"DNS = {dns_server}",
                f"",
                f"[Peer]",
                f"PublicKey = {self.server_pub}",
                f"Endpoint = {self.endpoint}",
                f"AllowedIPs = 0.0.0.0/0, ::/0",
                f"PersistentKeepalive = 25",
            ]
            return "\n".join(lines)


class IPsecConfigGenerator:
    """Generates enterprise strongSwan swanctl.conf for site-to-site IPsec tunnels."""

    @classmethod
    def generate_swanctl_conf(cls, site_name: str, local_ip: str, remote_ip: str,
                              local_subnets: List[str], remote_subnets: List[str],
                              psk_secret: str) -> str:
        """Generates modern IKEv2 site-to-site configuration using AES-256-GCM and SHA384."""
        conn_name = f"s2s-{site_name.lower().replace(' ', '-')}"
        loc_sub = ", ".join(local_subnets)
        rem_sub = ", ".join(remote_subnets)

        conf = f"""# strongSwan swanctl.conf generated by SentinelFW
connections {{
    {conn_name} {{
        version = 2
        local_addrs = {local_ip}
        remote_addrs = {remote_ip}
        proposals = aes256gcm16-sha384-modp3072,aes256-sha256-modp2048

        local {{
            auth = psk
            id = {local_ip}
        }}
        remote {{
            auth = psk
            id = {remote_ip}
        }}
        children {{
            {conn_name}-net {{
                local_ts = {loc_sub}
                remote_ts = {rem_sub}
                esp_proposals = aes256gcm16-modp3072,aes256-sha256
                start_action = start
                dpd_action = restart
            }}
        }}
    }}
}}

secrets {{
    ike-{conn_name} {{
        id-1 = {local_ip}
        id-2 = {remote_ip}
        secret = "{psk_secret}"
    }}
}}
"""
        return conf
