package vpn

import (
	"bytes"
	"fmt"
)

// IPsecTunnelConfig specifies a route-based site-to-site tunnel.
type IPsecTunnelConfig struct {
	Name            string `json:"name"`
	LocalGateway    string `json:"local_gateway"`
	RemoteGateway   string `json:"remote_gateway"`
	PreSharedKey    string `json:"psk"`
	LocalSubnet     string `json:"local_subnet"`
	RemoteSubnet    string `json:"remote_subnet"`
	IKEProposal     string `json:"ike_proposal"` // e.g. "aes256gcm16-prfsha384-ecp384"
	ESPProposal     string `json:"esp_proposal"` // e.g. "aes256gcm16-ecp384"
	DeadPeerTimeout int    `json:"dpd_timeout"`  // seconds
	VTIInterface    string `json:"vti_interface"` // e.g. "vti0"
}

// GenerateStrongSwanSwanctlConfig generates modern swanctl.conf for strongSwan.
func GenerateStrongSwanSwanctlConfig(tunnels []IPsecTunnelConfig) string {
	var b bytes.Buffer

	b.WriteString("# swanctl.conf generated by SentinelGate\n")
	b.WriteString("connections {\n")

	for _, t := range tunnels {
		b.WriteString(fmt.Sprintf("    %s {\n", t.Name))
		b.WriteString(fmt.Sprintf("        local_addrs = %s\n", t.LocalGateway))
		b.WriteString(fmt.Sprintf("        remote_addrs = %s\n", t.RemoteGateway))
		b.WriteString("        version = 2\n")
		b.WriteString(fmt.Sprintf("        proposals = %s\n", t.IKEProposal))
		b.WriteString("        local {\n            auth = psk\n        }\n")
		b.WriteString("        remote {\n            auth = psk\n        }\n")
		b.WriteString("        children {\n")
		b.WriteString(fmt.Sprintf("            %s-child {\n", t.Name))
		b.WriteString(fmt.Sprintf("                local_ts = %s\n", t.LocalSubnet))
		b.WriteString(fmt.Sprintf("                remote_ts = %s\n", t.RemoteSubnet))
		b.WriteString(fmt.Sprintf("                esp_proposals = %s\n", t.ESPProposal))
		b.WriteString(fmt.Sprintf("                dpd_action = restart\n"))
		b.WriteString(fmt.Sprintf("                if_id_in = 42\n                if_id_out = 42\n"))
		b.WriteString("            }\n        }\n    }\n")
	}

	b.WriteString("}\n\nsecrets {\n")
	for _, t := range tunnels {
		b.WriteString(fmt.Sprintf("    ike-%s {\n", t.Name))
		b.WriteString(fmt.Sprintf("        secret = %s\n", t.PreSharedKey))
		b.WriteString("    }\n")
	}
	b.WriteString("}\n")

	return b.String()
}
