// Package dnsfilter handles DNS configuration, RPZ response policy zones, and DHCP generation.
package dnsfilter

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/sentinelgate/sentinelgate/pkg/config"
)

// GenerateDnsmasqDHCP generates a dnsmasq configuration for enterprise DHCP scopes.
func GenerateDnsmasqDHCP(cfg *config.GatewayConfig) string {
	var b bytes.Buffer

	b.WriteString("# dnsmasq DHCP configuration generated by SentinelGate\n")
	b.WriteString("bind-interfaces\n")
	b.WriteString("except-interface=lo\n\n")

	for _, scope := range cfg.DHCP {
		b.WriteString(fmt.Sprintf("# Interface %s Scope\n", scope.Interface))
		b.WriteString(fmt.Sprintf("interface=%s\n", scope.Interface))
		lease := scope.LeaseTime
		if lease == "" {
			lease = "12h"
		}
		b.WriteString(fmt.Sprintf("dhcp-range=%s,%s,255.255.255.0,%s\n", scope.StartIP, scope.EndIP, lease))
		if scope.Gateway != "" {
			b.WriteString(fmt.Sprintf("dhcp-option=interface:%s,option:router,%s\n", scope.Interface, scope.Gateway))
		}
		if len(scope.DNS) > 0 {
			b.WriteString(fmt.Sprintf("dhcp-option=interface:%s,option:dns-server,%s\n", scope.Interface, strings.Join(scope.DNS, ",")))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// GenerateUnboundConfig generates an Unbound DNS resolver configuration with local sinkholing.
func GenerateUnboundConfig(cfg *config.GatewayConfig, blockedDomains []string) string {
	var b bytes.Buffer

	b.WriteString("# Unbound DNS configuration generated by SentinelGate\n")
	b.WriteString("server:\n")
	b.WriteString("    verbosity: 1\n")
	b.WriteString("    interface: 0.0.0.0\n")
	b.WriteString("    interface: ::0\n")
	b.WriteString("    access-control: 127.0.0.0/8 allow\n")
	b.WriteString("    access-control: 192.168.0.0/16 allow\n")
	b.WriteString("    access-control: 10.0.0.0/8 allow\n")
	b.WriteString("    access-control: 172.16.0.0/12 allow\n")
	b.WriteString("    hide-identity: yes\n")
	b.WriteString("    hide-version: yes\n")
	b.WriteString("    harden-glue: yes\n")
	b.WriteString("    harden-dnssec-stripped: yes\n\n")

	if len(blockedDomains) > 0 {
		b.WriteString("    # SentinelGate DNS Sinkhole Entries\n")
		for _, domain := range blockedDomains {
			b.WriteString(fmt.Sprintf("    local-zone: \"%s\" redirect\n", domain))
			b.WriteString(fmt.Sprintf("    local-data: \"%s A 0.0.0.0\"\n", domain))
		}
	}

	b.WriteString("\nforward-zone:\n")
	b.WriteString("    name: \".\"\n")
	b.WriteString("    forward-addr: 1.1.1.1\n")
	b.WriteString("    forward-addr: 8.8.8.8\n")

	return b.String()
}
