// Package sdwan provides FRRouting (FRR) configuration generation and SD-WAN path management.
package sdwan

import (
	"bytes"
	"fmt"

	"github.com/sentinelgate/sentinelgate/pkg/config"
)

// GenerateFRRConfig generates a production frr.conf from GatewayConfig.
func GenerateFRRConfig(cfg *config.GatewayConfig) string {
	var b bytes.Buffer

	b.WriteString("! FRRouting Configuration generated by SentinelGate\n")
	b.WriteString("frr version 8.5\nfrr defaults traditional\n")
	b.WriteString(fmt.Sprintf("hostname %s\n", cfg.System.Hostname))
	b.WriteString("log syslog informational\nservice integrated-vtysh-config\n!\n")

	// 1. Static Routes
	if len(cfg.StaticRoutes) > 0 {
		b.WriteString("! Static Routes\n")
		for _, r := range cfg.StaticRoutes {
			intf := ""
			if r.Interface != "" {
				intf = " " + r.Interface
			}
			b.WriteString(fmt.Sprintf("ip route %s %s%s\n", r.Destination, r.Gateway, intf))
		}
		b.WriteString("!\n")
	}

	// 2. BGP Configuration
	if cfg.BGP.Enabled && cfg.BGP.LocalASN > 0 {
		b.WriteString(fmt.Sprintf("router bgp %d\n", cfg.BGP.LocalASN))
		if cfg.BGP.RouterID != "" {
			b.WriteString(fmt.Sprintf(" bgp router-id %s\n", cfg.BGP.RouterID))
		}
		for _, n := range cfg.BGP.Neighbors {
			b.WriteString(fmt.Sprintf(" neighbor %s\n", n))
		}
		for _, net := range cfg.BGP.Networks {
			b.WriteString(fmt.Sprintf(" network %s\n", net))
		}
		b.WriteString("!\n")
	}

	b.WriteString("line vty\n!\n")
	return b.String()
}
