// Package ha manages active-passive high availability (VRRP), conntrack session replication,
// and split-brain fencing for SentinelGate.
package ha

import (
	"bytes"
	"fmt"
	"sync"
	"time"
)

// NodeRole represents the HA operational state of this appliance.
type NodeRole string

const (
	RoleMaster NodeRole = "MASTER"
	RoleBackup NodeRole = "BACKUP"
	RoleFault  NodeRole = "FAULT"
)

// HAConfig specifies the cluster and failover parameters.
type HAConfig struct {
	VirtualRouterID int      `json:"vrid"`
	Priority        int      `json:"priority"` // Higher = preferred master
	AuthPass        string   `json:"auth_pass"`
	SyncInterface   string   `json:"sync_interface"`
	PeerIP          string   `json:"peer_ip"`
	VirtualIPs      []string `json:"virtual_ips"` // e.g. "198.51.100.1/24 dev eth0", "192.168.10.1/24 dev eth1"
	TrackInterfaces []string `json:"track_interfaces"`
	WitnessIP       string   `json:"witness_ip"` // Ping witness for fencing
}

// FailoverManager orchestrates keepalived, conntrackd, and split-brain fencing.
type FailoverManager struct {
	mu           sync.RWMutex
	cfg          HAConfig
	currentRole  NodeRole
	lastHeartbeat time.Time
	sessionsSynced uint64
}

// NewFailoverManager creates a new HA manager instance.
func NewFailoverManager(cfg HAConfig) *FailoverManager {
	initialRole := RoleBackup
	if cfg.Priority > 100 {
		initialRole = RoleMaster
	}
	return &FailoverManager{
		cfg:         cfg,
		currentRole: initialRole,
		lastHeartbeat: time.Now(),
	}
}

// GenerateKeepalivedConf compiles a production keepalived configuration.
func GenerateKeepalivedConf(cfg *HAConfig) string {
	var b bytes.Buffer

	b.WriteString("# keepalived.conf generated by SentinelGate\n")
	b.WriteString("global_defs {\n    router_id SentinelGate_HA\n    enable_script_security\n}\n\n")

	b.WriteString(fmt.Sprintf("vrrp_instance SG_HA_%d {\n", cfg.VirtualRouterID))
	b.WriteString(fmt.Sprintf("    state %s\n", "BACKUP")) // Start as BACKUP, election chooses master
	b.WriteString(fmt.Sprintf("    interface %s\n", cfg.SyncInterface))
	b.WriteString(fmt.Sprintf("    virtual_router_id %d\n", cfg.VirtualRouterID))
	b.WriteString(fmt.Sprintf("    priority %d\n", cfg.Priority))
	b.WriteString("    advert_int 1\n")
	b.WriteString("    authentication {\n        auth_type PASS\n")
	b.WriteString(fmt.Sprintf("        auth_pass %s\n    }\n", cfg.AuthPass))

	b.WriteString("    virtual_ipaddress {\n")
	for _, vip := range cfg.VirtualIPs {
		b.WriteString(fmt.Sprintf("        %s\n", vip))
	}
	b.WriteString("    }\n")

	if len(cfg.TrackInterfaces) > 0 {
		b.WriteString("    track_interface {\n")
		for _, itf := range cfg.TrackInterfaces {
			b.WriteString(fmt.Sprintf("        %s\n", itf))
		}
		b.WriteString("    }\n")
	}

	b.WriteString("}\n")
	return b.String()
}

// GenerateConntrackdConf compiles a real-time state sync configuration for conntrackd.
func GenerateConntrackdConf(cfg *HAConfig) string {
	var b bytes.Buffer

	b.WriteString("# conntrackd.conf generated by SentinelGate (Real-Time Mode)\n")
	b.WriteString("Sync {\n    Mode FTFW {\n        ResendQueueSize 131072\n        CommitTimeout 180\n")
	b.WriteString("        PurgeTimeout 60\n    }\n")
	b.WriteString("    UDP {\n")
	b.WriteString(fmt.Sprintf("        IPv4_interface %s\n", cfg.SyncInterface))
	b.WriteString(fmt.Sprintf("        IPv4_Destination %s\n", cfg.PeerIP))
	b.WriteString("        Port 3780\n        Checksum on\n    }\n}\n")
	b.WriteString("General {\n    Systemd on\n    HashSize 32768\n    HashLimit 131072\n}\n")

	return b.String()
}

// TransitionRole updates the node role following VRRP election.
func (fm *FailoverManager) TransitionRole(newRole NodeRole) {
	fm.mu.Lock()
	defer fm.mu.Unlock()
	fm.currentRole = newRole
	fm.lastHeartbeat = time.Now()
}

// GetRole returns the active HA role.
func (fm *FailoverManager) GetRole() NodeRole {
	fm.mu.RLock()
	defer fm.mu.RUnlock()
	return fm.currentRole
}
